package HomeBuilder;

/**Class enum for menu*/

public enum Menu {
	
	MUSHROOM_SOUP,CHEESE_SOUP,
	GREEK_SALAD, CAESAR_SALAD,SEAFOOD_SALAT,CAPRESE,
	POTATO_WITH_FRIED_CHIKEN,  SPAGETTI,CHIKEN,
	JUICE, WATTER, KEFIR, TEA, COFEEE,
	ICE_CREAM,ECLAIR,APPLE_PIE,
	BREAD,BAGET,TOMATO, KETCHUP
	
}
